apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
      matchLabels:
        app: cluster-autoscaler
  template:
    spec:
      containers:
        - name: cluster-autoscaler
          args:
          - --kubeconfig=/mnt/capi-prod.kubeconfig
          - --clusterapi-cloud-config-authoritative
          - --cloud-provider=clusterapi
          - --node-group-auto-discovery=clusterapi:clusterName=capi-prod
      volumes:
      - name: kubeconfig-vol
        configMap:
          name: capi-prod-kubeconfig

  