apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-kubeconfig
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: fetch-kubeconfig
        image: bitnami/kubectl:1.26.3
        command:
        - /bin/sh
        - -c
        - |
          kubectl get secret capi-gcp-kubeconfig -o jsonpath='{.data.value}' | base64 --decode | kubectl create configmap -n kube-system capi-gcp-kubeconfig --from-file=capi-gcp.kubeconfig=/dev/stdin
      restartPolicy: Never
