apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-role-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: job-service-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: job-cluster-role
  apiGroup: rbac.authorization.k8s.io
