apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-kubeconfig
spec:
  template:
    spec:
      serviceAccountName: job-service-account
      containers:
      - name: fetch-kubeconfig
        image: bitnami/kubectl:1.26.3
        command:
        - /bin/sh
        - -c
        - |
          kubectl get secret ${CLUSTER_NAME}-kubeconfig -o jsonpath='{.data.value}' | base64 --decode | kubectl create configmap -n kube-system ${CLUSTER_NAME}-kubeconfig --from-file=${CLUSTER_NAME}.kubeconfig=/dev/stdin
      restartPolicy: Never
